'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={projects:[],sessions:[],policies:{}},selected=null,token='',view='conversation',timer;
let taskRequest=null,sendRequest=null;
function notice(message,error=false){const n=$('#notice');(document.querySelector('dialog[open]')||document.body).append(n);n.textContent=message;n.className=error?'error':'';n.hidden=false;clearTimeout(timer);timer=setTimeout(()=>n.hidden=true,error?30000:5000)}
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-Factory-Token':token}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
async function busy(button,fn){button.disabled=true;try{await fn()}catch(e){notice(e.message,true)}finally{button.disabled=false}}
function projectOptions(){const current=$('#project').value;$('#project').innerHTML=state.projects.length?state.projects.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join(''):'<option value="">No repositories connected</option>';if(state.projects.some(p=>p.id===current))$('#project').value=current;$('#new-task').disabled=!state.policies[$('#project').value]}
function icon(name){return `<svg class="icon" aria-hidden="true"><use href="/assets/icons.svg#${name}"/></svg>`}
function agentLabel(name){return ({codex:'Codex','claude-code':'Claude Code',copilot:'Copilot',opencode:'OpenCode'})[name]||name||'Agent'}
function tone(s){if(s.statusReadiness!=='ready')return 'neutral';if(['ci_failed','changes_requested','needs_input'].includes(s.status))return 'red';if(['approved','mergeable','merged'].includes(s.status))return 'green';if(['review_pending','commented','draft'].includes(s.status))return 'amber';if(s.status==='working')return 'blue';return 'neutral'}
function sessionTags(s){return `<span class="tag agent">${icon('agents')}${esc(agentLabel(s.harness))}</span><span class="tag">${icon(s.kind==='orchestrator'?'grid':'terminal')}${s.kind==='orchestrator'?'Orchestrator':'Worker'}</span>`}
function board(){
  const pid=$('#project').value,sessions=state.sessions.filter(s=>s.projectId===pid);
  $('#repos').textContent=state.projects.length;
  $('#workers').textContent=state.sessions.length;
  $('#prs').textContent=state.sessions.reduce((a,s)=>a+(s.prs||[]).length,0);
  $('#attention').textContent=state.sessions.filter(s=>['needs_input','ci_failed','changes_requested'].includes(s.status)).length;
  if(!sessions.length){
    $('#board').innerHTML=`<div class="empty"><div class="empty-icon">${icon('repo')}</div><h2>${state.projects.length?'Ready for your next task.':'Start with a repository.'}</h2><p>${state.projects.length?'Dispatch a focused task, or have an orchestrator coordinate a larger goal.':'Connect a Git checkout and choose the CI checks every PR must pass.'}</p></div>`;
    return;
  }
  const lanes=[['building','Building','branch'],['validating','Validating','shield'],['needs_review','Human review','review'],['ready','Engine ready','check'],['archive','Archived','archive']];
  $('#board').innerHTML=lanes.filter(([key])=>sessions.some(s=>(s.kanbanColumn||'building')===key)).map(([key,label,glyph])=>{
    const rows=sessions.filter(s=>(s.kanbanColumn||'building')===key);
    return `<div class="lane"><div class="lane-title">${icon(glyph)}${label}<b>${rows.length}</b></div>${rows.map(s=>`<button class="card ${selected===s.id?'selected':''}" data-session="${esc(s.id)}"><div class="row"><strong>${esc(s.displayName||s.id)}</strong><span class="badge tone-${tone(s)}">${esc(s.statusReadiness==='ready'?s.displayStatus||s.status:'Checking runtime')}</span></div><div class="card-tags">${sessionTags(s)}</div><div class="branch-line">${icon('branch')}<span>${esc(s.branch||s.id)}</span></div>${(s.prs||[]).map(pr=>`<div class="pr-line">${icon('pull-request')}<span>${esc(pr.url||pr.prUrl||'Tracked pull request')}</span></div>`).join('')}</button>`).join('')}</div>`;
  }).join('');
  $('#board').querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>{selected=b.dataset.session;board();inspect()});
}
async function refresh(){try{state=await api('/api/state');token=state.token;$('#connection').textContent='Engine online';$('#connection').className='connection is-online';projectOptions();board()}catch(e){$('#connection').textContent='Engine offline';$('#connection').className='connection is-offline';notice(e.message,true)}}
async function inspect(preserve=false){const prior=$('#session-body .conversation');const scrollTop=preserve&&prior&&prior.scrollHeight-prior.scrollTop-prior.clientHeight>30?prior.scrollTop:null;if(!selected)return;const sid=selected,s=state.sessions.find(x=>x.id===sid);if(!s)return;$('#inspector').innerHTML=`<h2>${esc(s.displayName||s.id)}</h2><div class="session-tags">${sessionTags(s)}<span class="badge tone-${tone(s)}">${esc(s.statusReadiness==='ready'?s.displayStatus||s.status:'Checking runtime')}</span></div><div class="session-meta">${esc(s.id)}<br>${icon('branch')}${esc(s.branch||'Project orchestrator')}</div><div class="tabs"><button data-view="conversation" class="${view==='conversation'?'':'secondary'}">${icon('terminal')}Conversation</button><button data-view="reviews" class="${view==='reviews'?'':'secondary'}">${icon('review')}Review & handoff</button><button class="secondary" id="interrupt" aria-label="Interrupt agent" title="Interrupt agent">${icon('stop')}</button></div><div id="session-body">Loading native session…</div>`;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;inspect()});$('#interrupt').onclick=e=>busy(e.currentTarget,async()=>{await api(`/api/sessions/${sid}/interrupt`,{});notice('Interrupt requested')});
try{const d=await api(`/api/sessions/${sid}/${view}`);if(sid!==selected)return;if(view==='reviews'){const url=(s.prs||[])[0]?.url||(s.prs||[])[0]?.prUrl||'';$('#session-body').innerHTML=`<p>Review approvals and CI evidence must match the current PR head. The upstream board’s status is separate from this stricter handoff gate.</p><div class="pr-controls"><input id="pr-url" aria-label="Pull request URL" placeholder="https://github.com/owner/repo/pull/123" value="${esc(url)}"><div class="actions"><button id="review" class="secondary">${icon('review')}Run review</button><button id="gate">${icon('shield')}Check readiness</button></div></div><div id="gate-result"></div><div id="proof-result"></div><div class="conversation">${(d.runs||[]).map(r=>`<div class="message"><b>${esc(r.harness)} · ${esc(r.status)} · ${esc(r.verdict||'pending')}</b><code>${esc(r.targetSha)}</code><br>${esc(r.body)}</div>`).join('')||'<p>No review runs yet.</p>'}</div>`;loadProof(sid);$('#review').onclick=e=>busy(e.currentTarget,async()=>{await api(`/api/sessions/${sid}/review`,{prUrl:$('#pr-url').value});notice('Independent review requested; findings feed back to the worker.');inspect()});$('#gate').onclick=e=>busy(e.currentTarget,async()=>{const g=await api(`/api/sessions/${sid}/gate`,{prUrl:$('#pr-url').value});$('#gate-result').innerHTML=`<div class="gate ${g.ready?'pass':''}"><strong>${icon(g.ready?'check':'alert')}${g.ready?'Ready for human handoff':'Handoff blocked'}</strong><ul>${g.reasons.map(r=>`<li>${esc(r)}</li>`).join('')}</ul><code>${esc(g.headSha)}</code><p>${esc(g.meaning)}</p><small>${esc(g.observedAt)}</small></div>`})}else{renderConversation(d,sid,scrollTop)}}catch(e){if(sid===selected)$('#session-body').textContent=e.message}}
function renderConversation(d,sid,scrollTop=null){const entries=[...(d.messages||[]).map(m=>({...m,type:'message'})),...(d.activities||[]).map(a=>({...a,type:'activity'}))].sort((a,b)=>a.sequence-b.sequence);$('#session-body').innerHTML=`<small>Controller: ${esc(d.controller)} · durable native history</small><div class="conversation">${entries.map(m=>m.type==='message'?`<div class="message role-${esc(m.role)}"><b>${esc(m.role)}</b>${esc(m.text)}</div>`:`<div class="activity">${icon(m.activityKind==='command'?'terminal':'spark')}${esc(m.activityKind)} · ${esc(m.status)}<br>${esc(m.summary)}${approvalButtons(m)}</div>`).join('')||'<p>No messages yet.</p>'}</div><form class="send"><textarea aria-label="Message to agent" placeholder="Follow up with this agent…" required maxlength="14000"></textarea><button>${icon('send')}Send</button></form>`;$('#session-body .conversation').scrollTop=scrollTop??$('#session-body .conversation').scrollHeight;$('.send').onsubmit=async e=>{e.preventDefault();const text=$('.send textarea').value;if(!sendRequest||sendRequest.text!==text||sendRequest.sid!==sid)sendRequest={sid,text,id:crypto.randomUUID()};await busy($('.send button'),async()=>{await api(`/api/sessions/${sid}/send`,{text,requestId:sendRequest.id});sendRequest=null;await inspect()})};document.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>busy(b,async()=>{await api(`/api/sessions/${sid}/approval`,{requestId:b.dataset.request,decisionId:b.dataset.decision});inspect()}))}
function approvalButtons(a){if(a.activityKind!=='approval'||a.status!=='pending')return '';const d=a.detail||{},req=a.requestId||d.requestId||d.id;const choices=d.options||d.decisions||[];if(req===undefined||!Array.isArray(choices)||!choices.length)return '<small>Use the native AO client to resolve this approval.</small>';return `<div class="actions">${choices.map(o=>`<button class="secondary" data-request="${esc(req)}" data-decision="${esc(o.id||o.decisionId)}">${esc(o.label||o.name||o.id)}</button>`).join('')}</div>`}
$('#add-button').onclick=()=>$('#add').showModal();$('#new-task').onclick=()=>$('#task').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#project').onchange=()=>{selected=null;board();$('#new-task').disabled=!state.policies[$('#project').value]};
$('#add form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await busy(e.submitter,async()=>{const d=await api('/api/projects',{path:f.get('path'),requiredChecks:f.get('checks').split(','),harness:f.get('harness')});$('#add').close();await refresh();$('#project').value=d.project.id;board();notice('Repository connected. Native auto-review is enabled.');e.target.reset()})};
$('#task form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),body={projectId:$('#project').value,title:f.get('title'),prompt:f.get('prompt'),kind:f.get('kind')};const signature=JSON.stringify(body);if(!taskRequest||taskRequest.signature!==signature)taskRequest={signature,id:crypto.randomUUID()};body.requestId=taskRequest.id;await busy(e.submitter,async()=>{const d=await api('/api/spawn',body);taskRequest=null;$('#task').close();await refresh();selected=d.session.id;board();inspect();e.target.reset()})};
async function loadProof(sid){
  const container=$('#proof-result');
  try{
    const proof=await api(`/api/sessions/${sid}/proof`);
    if(sid!==selected||!container.isConnected)return;
    container.innerHTML=`<h3>Before / after evidence</h3>${proof.pairs.length?proof.pairs.map(pair=>`<details class="proof-pair"><summary>${esc(pair.criterion)}</summary><div class="proof-comparison">${['before','after'].map(phase=>{const p=pair[phase];return `<section><h4>${phase==='before'?'Before':'After'}</h4>${p?`<span class="badge tone-${p.passed?'green':'red'}">${p.passed?'Captured':'Capture failed'}</span><code>${esc(p.headSha)}</code><pre>${esc(p.command.join(' '))}</pre><small>Exit ${esc(p.exitCode)} · expected ${esc(p.expectedExitCode)}${p.timedOut?' · timed out':''}${p.outputTruncated?' · output truncated':''}</small><pre>${esc(p.output)}</pre>${(p.artifacts||[]).map(a=>a.mediaType.startsWith('image/')?`<a href="/api/proof-artifacts/${esc(a.id)}" target="_blank" rel="noopener"><img src="/api/proof-artifacts/${esc(a.id)}" alt="${esc(phase+' '+pair.criterion)}" loading="lazy"></a>`:`<video src="/api/proof-artifacts/${esc(a.id)}" controls preload="metadata"></video>`).join('')}`:'<p>Missing capture</p>'}</section>`}).join('')}</div></details>`).join(''):'<p>No captured evidence.</p>'}`;
  }catch(e){if(container.isConnected)container.textContent=e.message}
}
refresh();setInterval(async()=>{await refresh();if(selected&&view==='conversation'&&!$('#inspector').contains(document.activeElement))await inspect(true)},6000);
