'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={projects:[],sessions:[],policies:{}},selected=null,token='',view='conversation',timer;
let taskRequest=null,sendRequest=null;
function notice(message,error=false){const n=$('#notice');(document.querySelector('dialog[open]')||document.body).append(n);n.textContent=message;n.className=error?'error':'';n.hidden=false;clearTimeout(timer);timer=setTimeout(()=>n.hidden=true,error?30000:5000)}
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-Factory-Token':token}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
async function busy(button,fn){button.disabled=true;try{await fn()}catch(e){notice(e.message,true)}finally{button.disabled=false}}
function projectOptions(){const current=$('#project').value;$('#project').innerHTML=state.projects.length?state.projects.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join(''):'<option value="">No repositories connected</option>';if(state.projects.some(p=>p.id===current))$('#project').value=current;$('#new-task').disabled=!state.policies[$('#project').value]}
function board(){const pid=$('#project').value,sessions=state.sessions.filter(s=>s.projectId===pid);$('#repos').textContent=state.projects.length;$('#workers').textContent=state.sessions.length;$('#prs').textContent=state.sessions.reduce((a,s)=>a+(s.prs||[]).length,0);$('#attention').textContent=state.sessions.filter(s=>['needs_input','ci_failed','changes_requested'].includes(s.status)).length;
if(!sessions.length){$('#board').innerHTML=`<div class="empty"><div class="empty-icon">▧</div><h2>${state.projects.length?'Your production floor is ready.':'Start with a repository.'}</h2><p>${state.projects.length?'Dispatch a focused task or let a project orchestrator delegate a larger goal.':'Connect a Git checkout and choose the CI checks every PR must pass.'}</p></div>`;return}
const lanes=[['building','Building'],['validating','Validating'],['needs_review','Human review'],['ready','Upstream ready'],['archive','Archived']];$('#board').innerHTML=lanes.filter(([key])=>sessions.some(s=>(s.kanbanColumn||'building')===key)).map(([key,label])=>{const rows=sessions.filter(s=>(s.kanbanColumn||'building')===key);return `<div class="lane"><div class="lane-title">${label}<b>${rows.length}</b></div>${rows.map(s=>`<button class="card ${selected===s.id?'selected':''}" data-session="${esc(s.id)}"><div class="row"><strong>${esc(s.displayName||s.id)}</strong><span class="badge">${esc(s.statusReadiness==='ready'?s.displayStatus||s.status:'Checking runtime')}</span></div><p>${esc(s.harness)} · ${esc(s.kind)} · ${esc(s.branch||s.id)}</p>${(s.prs||[]).map(pr=>`<p>${esc(pr.url||pr.prUrl||'Tracked pull request')}</p>`).join('')}</button>`).join('')}</div>`}).join('');$('#board').querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>{selected=b.dataset.session;board();inspect()})}
async function refresh(){try{state=await api('/api/state');token=state.token;$('#connection').textContent='● Engine online · live state';projectOptions();board()}catch(e){$('#connection').textContent='Engine unavailable';notice(e.message,true)}}
async function inspect(preserve=false){const prior=$('#session-body .conversation');const scrollTop=preserve&&prior&&prior.scrollHeight-prior.scrollTop-prior.clientHeight>30?prior.scrollTop:null;if(!selected)return;const sid=selected,s=state.sessions.find(x=>x.id===sid);if(!s)return;$('#inspector').innerHTML=`<h2>${esc(s.displayName||s.id)}</h2><div class="session-meta">${esc(s.id)} · ${esc(s.harness)}<br>${esc(s.branch||'Project orchestrator')}</div><div class="tabs"><button data-view="conversation" class="${view==='conversation'?'':'secondary'}">Conversation</button><button data-view="reviews" class="${view==='reviews'?'':'secondary'}">Review & handoff</button><button class="secondary" id="interrupt">Interrupt</button></div><div id="session-body">Loading native session…</div>`;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;inspect()});$('#interrupt').onclick=e=>busy(e.target,async()=>{await api(`/api/sessions/${sid}/interrupt`,{});notice('Interrupt requested')});
try{const d=await api(`/api/sessions/${sid}/${view}`);if(sid!==selected)return;if(view==='reviews'){const url=(s.prs||[])[0]?.url||(s.prs||[])[0]?.prUrl||'';$('#session-body').innerHTML=`<p>Review approvals and CI evidence must match the current PR head. The upstream board’s status is separate from this stricter handoff gate.</p><div class="pr-controls"><input id="pr-url" aria-label="Pull request URL" placeholder="https://github.com/owner/repo/pull/123" value="${esc(url)}"><div class="actions"><button id="review" class="secondary">Run independent review</button><button id="gate">Check readiness</button></div></div><div id="gate-result"></div><div class="conversation">${(d.runs||[]).map(r=>`<div class="message"><b>${esc(r.harness)} · ${esc(r.status)} · ${esc(r.verdict||'pending')}</b><code>${esc(r.targetSha)}</code><br>${esc(r.body)}</div>`).join('')||'<p>No review runs yet.</p>'}</div>`;$('#review').onclick=e=>busy(e.target,async()=>{await api(`/api/sessions/${sid}/review`,{prUrl:$('#pr-url').value});notice('Independent review requested; findings feed back to the worker.');inspect()});$('#gate').onclick=e=>busy(e.target,async()=>{const g=await api(`/api/sessions/${sid}/gate`,{prUrl:$('#pr-url').value});$('#gate-result').innerHTML=`<div class="gate ${g.ready?'pass':''}"><strong>${g.ready?'Ready for human handoff':'Handoff blocked'}</strong><ul>${g.reasons.map(r=>`<li>${esc(r)}</li>`).join('')}</ul><code>${esc(g.headSha)}</code><p>${esc(g.meaning)}</p><small>${esc(g.observedAt)}</small></div>`})}else{renderConversation(d,sid,scrollTop)}}catch(e){if(sid===selected)$('#session-body').textContent=e.message}}
function renderConversation(d,sid,scrollTop=null){const entries=[...(d.messages||[]).map(m=>({...m,type:'message'})),...(d.activities||[]).map(a=>({...a,type:'activity'}))].sort((a,b)=>a.sequence-b.sequence);$('#session-body').innerHTML=`<small>Controller: ${esc(d.controller)} · durable native history</small><div class="conversation">${entries.map(m=>m.type==='message'?`<div class="message"><b>${esc(m.role)}</b>${esc(m.text)}</div>`:`<div class="activity">${esc(m.activityKind)} · ${esc(m.status)}<br>${esc(m.summary)}${approvalButtons(m)}</div>`).join('')||'<p>No messages yet.</p>'}</div><form class="send"><textarea aria-label="Message to agent" placeholder="Follow up with this agent…" required maxlength="14000"></textarea><button>Send</button></form>`;$('#session-body .conversation').scrollTop=scrollTop??$('#session-body .conversation').scrollHeight;$('.send').onsubmit=async e=>{e.preventDefault();const text=$('.send textarea').value;if(!sendRequest||sendRequest.text!==text||sendRequest.sid!==sid)sendRequest={sid,text,id:crypto.randomUUID()};await busy($('.send button'),async()=>{await api(`/api/sessions/${sid}/send`,{text,requestId:sendRequest.id});sendRequest=null;await inspect()})};document.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>busy(b,async()=>{await api(`/api/sessions/${sid}/approval`,{requestId:b.dataset.request,decisionId:b.dataset.decision});inspect()}))}
function approvalButtons(a){if(a.activityKind!=='approval'||a.status!=='pending')return '';const d=a.detail||{},req=a.requestId||d.requestId||d.id;const choices=d.options||d.decisions||[];if(req===undefined||!Array.isArray(choices)||!choices.length)return '<small>Use the native AO client to resolve this approval.</small>';return `<div class="actions">${choices.map(o=>`<button class="secondary" data-request="${esc(req)}" data-decision="${esc(o.id||o.decisionId)}">${esc(o.label||o.name||o.id)}</button>`).join('')}</div>`}
$('#add-button').onclick=()=>$('#add').showModal();$('#new-task').onclick=()=>$('#task').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#project').onchange=()=>{selected=null;board();$('#new-task').disabled=!state.policies[$('#project').value]};
$('#add form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await busy(e.submitter,async()=>{const d=await api('/api/projects',{path:f.get('path'),requiredChecks:f.get('checks').split(','),harness:f.get('harness')});$('#add').close();await refresh();$('#project').value=d.project.id;board();notice('Repository connected. Native auto-review is enabled.');e.target.reset()})};
$('#task form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),body={projectId:$('#project').value,title:f.get('title'),prompt:f.get('prompt'),kind:f.get('kind')};const signature=JSON.stringify(body);if(!taskRequest||taskRequest.signature!==signature)taskRequest={signature,id:crypto.randomUUID()};body.requestId=taskRequest.id;await busy(e.submitter,async()=>{const d=await api('/api/spawn',body);taskRequest=null;$('#task').close();await refresh();selected=d.session.id;board();inspect();e.target.reset()})};
refresh();setInterval(async()=>{await refresh();if(selected&&view==='conversation'&&!$('#inspector').contains(document.activeElement))await inspect(true)},6000);
